# Generated by Django 5.0 on 2023-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.IntegerField(null=True)),
                ('p', models.IntegerField(null=True)),
                ('k', models.IntegerField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('rainfall', models.FloatField(null=True)),
                ('output', models.TextField(default='Undefined')),
            ],
        ),
    ]
