# Generated by Django 5.0 on 2023-12-13 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definer',
            old_name='p',
            new_name='P',
        ),
        migrations.AddField(
            model_name='definer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='definer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
