# Generated by Django 5.0 on 2023-12-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_p_definer_p_definer_created_definer_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definer',
            name='updated',
        ),
    ]
